/* Generated By:JavaCC: Do not edit this line. DoSaParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DoSaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SESSO = 6;
  /** RegularExpression Id. */
  int TIPO = 7;
  /** RegularExpression Id. */
  int GRUPPOSANGUIGNO = 8;
  /** RegularExpression Id. */
  int RH = 9;
  /** RegularExpression Id. */
  int IDONEITA = 10;
  /** RegularExpression Id. */
  int TIPODONAZIONE = 11;
  /** RegularExpression Id. */
  int UNITARACCOLTA = 12;
  /** RegularExpression Id. */
  int EMAIL = 13;
  /** RegularExpression Id. */
  int IDENTIFICATOR = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int NUM = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "<SESSO>",
    "<TIPO>",
    "<GRUPPOSANGUIGNO>",
    "<RH>",
    "<IDONEITA>",
    "<TIPODONAZIONE>",
    "\"Unit\\u00e0 Raccolta Fissa\"",
    "<EMAIL>",
    "<IDENTIFICATOR>",
    "<ID>",
    "<NUM>",
    "\".\"",
    "\"***GRUPPO DONATORI***\"",
    "\"- NUMERO:\"",
    "\"- DATA FONDAZIONE:\"",
    "\"- PRESIDENTE:\"",
    "\"-\"",
    "\"- SEGRETARIO:\"",
    "\"- NUMERO ISCRITTI:\"",
    "\";\"",
    "\"***DONATORE***\"",
    "\"- SESSO:\"",
    "\"- DATA NASCITA:\"",
    "\"- STATO NASCITA:\"",
    "\"- TELEFONO FISSO:\"",
    "\"- TELEFONO CELLULARE:\"",
    "\"- CITTADINANZA:\"",
    "\"- GRUPPO SANGUIGNO:\"",
    "\"- RH:\"",
    "\"- DATA ISCRIZIONE:\"",
    "\"- GRUPPO LOCALE:\"",
    "\"- TESSERA GRUPPO LOCALE:\"",
    "\"***DONAZIONE***\"",
    "\"- DATA DONAZIONE:\"",
    "\"- UNITA\\\' RACCOLTA:\"",
    "\"- COMUNE DONAZIONE:\"",
    "\"- ASL DONAZIONE:\"",
    "\"- PUNTO PRELIEVO:\"",
    "\"- INDIRIZZO:\"",
    "\"- CAP:\"",
    "\"- COMUNE:\"",
    "\"- STATO:\"",
    "\"- SEZIONE:\"",
    "\"- CODICE FISCALE:\"",
    "\"/\"",
    "\"- EMAIL:\"",
    "\"- IDONEO:\"",
    "\"- PROSSIMA DATA DISPONIBILE PER DONAZIONE:\"",
    "\"- TIPOLOGIA DONATORE:\"",
    "\"- TIPO DI DONAZIONE:\"",
    "\"- DONATORE:\"",
    "\"- NUMERO DI DONAZIONI:\"",
    "\"Nome:\"",
    "\"- NOME:\"",
    "\"Cognome:\"",
    "\"- COGNOME:\"",
  };

}
