/* Generated by JTB 1.4.7 */
package parser.visitor;

import parser.syntaxtree.*;

public interface IVoidVisitor {

  public void visit(final NodeChoice n);

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeTCF n);

  public void visit(final NodeToken n);

  public void visit(final Scope n);

  public void visit(final Gruppo n);

  public void visit(final Donatore n);

  public void visit(final Donazione n);

  public void visit(final Indirizzo n);

  public void visit(final Sezione n);

  public void visit(final CodiceFiscale n);

  public void visit(final Telefono n);

  public void visit(final EMail n);

  public void visit(final Idoneo n);

  public void visit(final DataProssimaDonazione n);

  public void visit(final TipoDonatore n);

  public void visit(final TipoDonazione n);

  public void visit(final DatiDonatore n);

  public void visit(final NumeroDonazioni n);

  public void visit(final Nome n);

  public void visit(final Cognome n);

  public void visit(final Data n);

}
