/* Generated by JTB 1.4.7 */
package parser.syntaxtree;

import parser.visitor.*;

public class Donatore implements INode {

  public NodeToken f0;

  public Nome f1;

  public Cognome f2;

  public NodeToken f3;

  public NodeToken f4;

  public NodeToken f5;

  public Data f6;

  public NodeToken f7;

  public NodeToken f8;

  public CodiceFiscale f9;

  public Indirizzo f10;

  public NodeTelefono f11;

  public NodeTelefono f12;

  public NodeOptional f13;

  public NodeToken f14;

  public NodeToken f15;

  public NodeToken f16;

  public NodeToken f17;

  public NodeToken f18;

  public NodeToken f19;

  public NodeToken f20;

  public Data f21;

  public NodeToken f22;

  public NodeToken f23;

  public NodeToken f24;

  public NodeToken f25;

  public NumeroDonazioni f26;

  public Idoneo f27;

  public DataProssimaDonazione f28;

  public TipoDonatore f29;

  public NodeToken f30;

  public Sezione f31;

  public NodeToken f32;

  private static final long serialVersionUID = 147L;

  public Donatore(final NodeToken n0, final Nome n1, final Cognome n2, final NodeToken n3, final NodeToken n4, final NodeToken n5, final Data n6, final NodeToken n7, final NodeToken n8, final CodiceFiscale n9, final Indirizzo n10, final NodeTelefono n11, final NodeTelefono n12, final NodeOptional n13, final NodeToken n14, final NodeToken n15, final NodeToken n16, final NodeToken n17, final NodeToken n18, final NodeToken n19, final NodeToken n20, final Data n21, final NodeToken n22, final NodeToken n23, final NodeToken n24, final NodeToken n25, final NumeroDonazioni n26, final Idoneo n27, final DataProssimaDonazione n28, final TipoDonatore n29, final NodeToken n30, final Sezione n31, final NodeToken n32) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
    f9 = n9;
    f10 = n10;
    f11 = n11;
    f12 = n12;
    f13 = n13;
    f14 = n14;
    f15 = n15;
    f16 = n16;
    f17 = n17;
    f18 = n18;
    f19 = n19;
    f20 = n20;
    f21 = n21;
    f22 = n22;
    f23 = n23;
    f24 = n24;
    f25 = n25;
    f26 = n26;
    f27 = n27;
    f28 = n28;
    f29 = n29;
    f30 = n30;
    f31 = n31;
    f32 = n32;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
