/* Generated by JTB 1.4.7 */
package parser.syntaxtree;

import parser.visitor.*;

public class Gruppo implements INode {

  public NodeToken f0;

  public Nome f1;

  public NodeToken f2;

  public NodeToken f3;

  public NodeToken f4;

  public Data f5;

  public Indirizzo f6;

  public EMail f7;

  public NodeToken f8;

  public Nome f9;

  public NodeToken f10;

  public Cognome f11;

  public NodeToken f12;

  public Nome f13;

  public NodeToken f14;

  public Cognome f15;

  public NodeToken f16;

  public NodeToken f17;

  public NodeOptional f18;

  public NodeToken f19;

  private static final long serialVersionUID = 147L;

  public Gruppo(final NodeToken n0, final Nome n1, final NodeToken n2, final NodeToken n3, final NodeToken n4, final Data n5, final Indirizzo n6, final EMail n7, final NodeToken n8, final Nome n9, final NodeToken n10, final Cognome n11, final NodeToken n12, final Nome n13, final NodeToken n14, final Cognome n15, final NodeToken n16, final NodeToken n17, final NodeOptional n18, final NodeToken n19) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
    f9 = n9;
    f10 = n10;
    f11 = n11;
    f12 = n12;
    f13 = n13;
    f14 = n14;
    f15 = n15;
    f16 = n16;
    f17 = n17;
    f18 = n18;
    f19 = n19;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
